pipeline {
    agent any
    
     tools {
        maven 'maven 3.9'     // Must match Global Tool Configuration nassrrrss
        jdk 'jdk17'          // Must match Global Tool Configuratioee neamersddsdde
    }

   

    stages {
        
        stage('compile') {
            steps {
               dir('Boardgame-main') {
               sh 'mvn compile'
        }
        }
        }
        stage('package') {
            steps {
               dir('Boardgame-main') {
               sh 'mvn compile'
        } 
        }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}
